pipeline{
    agent any
    tools{
        maven 'Maven-3.9.16'
    }
    stages{

        stage('Build & Compile'){
            steps{
                echo "Compiling source code and downloading dependencies..."
                sh 'mvn clean compile'
            }
        }

        stage('Unit & Application Tests'){
            steps{
                echo "Running unit tests..."
                sh 'mvn test'
            }
        }

    }
    post {
        always{
            junit 'build/reports/**/*.xml'
        }
    }

    stage('Package Artifact'){
        steps{
            echo "Building the application..."
            sh 'mvn package -DskipTests'
        }
    }

    stage('Blackbox testing'){
        steps{
            echo "Running blackbox tests..."
        }
    }
}